### ISSUE TITLE
Infografía 

### ISSUE THREAD

**Issue by edgarmauricio123** [SistemasTecTlaxiaco/infografia-de-hilos-edgarmauricio123#2]
![HILOS](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-edgarmauricio123/assets/112227375/ec387d54-2aee-4661-8ed3-26eb04d35265)

**Comment by AmeliReyesHernandez** [comment]
20 %

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
